# Generated by Django 3.0.5 on 2020-10-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_auto_20201020_1923'), ('users', '0003_auto_20201020_1923'), ('users', '0004_remove_myuser_date_of_birth'), ('users', '0005_auto_20201020_1929'), ('users', '0006_auto_20201020_1933'), ('users', '0007_auto_20201020_1939'), ('users', '0008_auto_20201020_2025'), ('users', '0009_myuser_confirmation_code'), ('users', '0010_auto_20201021_0647'), ('users', '0011_auto_20201021_0711'), ('users', '0012_auto_20201021_0820'), ('users', '0013_auto_20201021_0822'), ('users', '0014_auto_20201021_1024'), ('users', '0015_auto_20201021_1031'), ('users', '0016_auto_20201021_1033'), ('users', '0017_auto_20201021_1337'), ('users', '0018_auto_20201021_1819'), ('users', '0019_auto_20201021_1821'), ('users', '0020_auto_20201021_1821'), ('users', '0021_auto_20201021_1825'), ('users', '0022_auto_20201021_1852'), ('users', '0023_auto_20201021_2021'), ('users', '0024_auto_20201022_0359')]

    initial = True

    dependencies = [
        ('admin', '0004_auto_20201020_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='Input e-mail', max_length=255, unique=True, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, help_text='Add description', verbose_name='Description')),
                ('first_name', models.CharField(blank=True, help_text='Input first name', max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text='Input last name', max_length=150, verbose_name='Last Name')),
                ('username', models.CharField(help_text='Input username', max_length=150, unique=True, verbose_name='Username')),
                ('confirmation_code', models.CharField(help_text='Input confirmation code', max_length=128, verbose_name='Confirmation Code')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('moderator', 'moderator'), ('user', 'user')], default='user', max_length=30)),
            ],
            options={
                'abstract': False,
                'ordering': ['email'],
            },
        ),
    ]
