# Generated by Django 3.0.5 on 2020-10-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='Input username', max_length=150, unique=True, verbose_name='Username')),
                ('email', models.EmailField(help_text='Input e-mail', max_length=255, unique=True, verbose_name='E-mail')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('moderator', 'moderator'), ('user', 'user')], default='user', max_length=30)),
                ('confirmation_code', models.CharField(help_text='Input confirmation code', max_length=128, verbose_name='Confirmation Code')),
                ('first_name', models.CharField(blank=True, help_text='Input first name', max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text='Input last name', max_length=150, verbose_name='Last Name')),
                ('bio', models.TextField(blank=True, help_text='Add description', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
