# Generated by Django 3.0.5 on 2020-10-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20201020_1929'),
        ('users', '0005_auto_20201020_1929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
