# Generated by Django 3.0.5 on 2020-10-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201020_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(help_text='Введите имя пользователя', max_length=150, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
