# Generated by Django 3.0.5 on 2020-10-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201020_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='description',
            field=models.TextField(blank=True, help_text='Add description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(help_text='Input e-mail', max_length=255, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, help_text='Input first name', max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, help_text='Input last name', max_length=150, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(help_text='Input username', max_length=150, null=True, unique=True, verbose_name='Username'),
        ),
    ]
