# Generated by Django 3.0.5 on 2020-10-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201020_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='confirmation_code',
            field=models.EmailField(default=1234, help_text='Input confirmation code', max_length=128, verbose_name='Confirmation Code'),
            preserve_default=False,
        ),
    ]
