# Generated by Django 3.0.5 on 2020-10-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201021_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(default='18094', help_text='Input confirmation code', max_length=128, verbose_name='Confirmation Code'),
        ),
    ]
