# Generated by Django 3.0.5 on 2020-10-21 07:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201021_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('944cd4da-f277-426c-b4b1-4d03012461f5'), help_text='Input confirmation code', max_length=128, verbose_name='Confirmation Code'),
        ),
    ]
