# Generated by Django 3.0.5 on 2020-10-21 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201021_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Freshman'), ('moderator', 'Sophomore'), ('user', 'Junior')], default='user', max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('a5c57d4c-866d-443f-ad7a-762387ef3ace'), help_text='Input confirmation code', max_length=128, verbose_name='Confirmation Code'),
        ),
    ]
