# Generated by Django 3.0.5 on 2020-10-21 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201021_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('f5a32677-c2ef-4a1f-a8e8-6b21901cc2af'), help_text='Input confirmation code', max_length=128, verbose_name='Confirmation Code'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('moderator', 'moderator'), ('user', 'user')], default='user', max_length=30),
        ),
    ]
