# Generated by Django 3.0.5 on 2020-10-21 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201021_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('44035657-cb67-40ae-ba44-99c0de8a04b1'), help_text='Input confirmation code', max_length=128, verbose_name='Confirmation Code'),
        ),
    ]
