# Generated by Django 3.0.5 on 2020-10-21 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201021_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('31f05d85-866e-464c-b58a-b17eab7d701a'), help_text='Input confirmation code', max_length=128, verbose_name='Confirmation Code'),
        ),
    ]
