# Generated by Django 3.0.5 on 2020-10-21 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201021_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('b9c98b39-1475-4235-9300-5b6dc2fa11bb'), help_text='Input confirmation code', max_length=128, verbose_name='Confirmation Code'),
        ),
    ]
