# Generated by Django 3.0.5 on 2020-10-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20201021_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(help_text='Input confirmation code', max_length=128, verbose_name='Confirmation Code'),
        ),
    ]
