# Generated by Django 3.0.5 on 2020-10-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20201021_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='description',
            new_name='bio',
        ),
    ]
