# Generated by Django 3.0.5 on 2020-10-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20201021_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['email']},
        ),
    ]
