# Generated by Django 3.0.5 on 2020-10-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20201021_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(help_text='Input username', max_length=150, unique=True, verbose_name='Username'),
        ),
    ]
