# Generated by Django 3.0.5 on 2020-10-31 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201031_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='confirmation_code',
        ),
    ]
