# Generated by Django 3.0.5 on 2020-10-31 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201031_1616'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('author', 'review')},
        ),
    ]
