# Generated by Django 3.0.5 on 2020-10-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20201026_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
