# Generated by Django 3.0.5 on 2020-10-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_titles_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ['pk']},
        ),
    ]
